### ISSUE TITLE
BotoServerError: BotoServerError: 400 Bad Request from development machine

### ISSUE THREAD

**Issue by hasan151623** [django-ses/django-ses#164]
Dear all,
I am trying to send email from my development machine with required parameters. It is not working. It shows following response:
**[NB: But It is working at production server.]**
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/hasan/.VENVS/venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/hasan/.VENVS/venv/local/lib/python2.7/site-packages/django_ses/__init__.py", line 164, in send_messages
    dkim_headers=self.dkim_headers)
  File "/home/hasan/.VENVS/venv/local/lib/python2.7/site-packages/boto/ses/connection.py", line 323, in send_raw_email
    return self._make_request('SendRawEmail', params)
  File "/home/hasan/.VENVS/venv/local/lib/python2.7/site-packages/boto/ses/connection.py", line 119, in _make_request
    self._handle_error(response, body)
  File "/home/hasan/.VENVS/venv/local/lib/python2.7/site-packages/boto/ses/connection.py", line 177, in _handle_error
    raise ExceptionToRaise(response.status, exc_reason, body)

BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>Empty required header 'To'.</Message>
  </Error>
  <RequestId>ff83b8c7-22b8-11e9-bd4f-57a4431a7fc1</RequestId>
</ErrorResponse>
```

Any help is highly appreciated.

**Comment by Aarbel** [comment]
@hasan151623 what was your solution ?
