### ISSUE TITLE
UnrecognizedClientException when calling the GetAccount operation

### ISSUE THREAD

**Issue by Cyb3rFl3x** [django-ses/django-ses#283]
Hello to you all, 

currently, I try to implement django-ses but got some issues. I installed django==4.2.1 and django-ses==3.4.1.
After setting up aws ses and defined all variables as described, I tried sending a mail with the send_mail function from django.

**Following error occurred:**
```
An error occurred (InvalidClientTokenId) when calling the GetSendQuota operation: The security token included in the request is invalid.
```

I thought it's because I deactivated the SESv2 client. After activating it with the setting (```USE_SES_V2 = True``` ), I got the following error: 
```
An error occurred (UnrecognizedClientException) when calling the GetAccount operation: The security token included in the request is invalid.
```

I also tried it on a fresh Django project, but same issue here. 
Via AWS-CLI or boto3 lib, everything works without issues with the same ACCESS and SECURITY Keys.

Thanks for your answers.

BR, Felix

**Comment by pcraciunoiu** [comment]
@Cyb3rFl3x do you have a traceback as well? Could be helpful

**Comment by Cyb3rFl3x** [comment]
***First Traceback (without USE_SES_V2 = True):***
```
Internal Server Error: /app/
Traceback (most recent call last):
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/felix/Workspace/Stuff/django-ses-test/app/views.py", line 9, in index
    send_mail("test", "test", "felix.lehner1@gmail.com", ["felix.lehner1@gmail.com"], fail_silently=False)
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 161, in send_messages
    self._update_throttling()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 210, in _update_throttling
    rate_limit = self.get_rate_limit()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 305, in get_rate_limit
    return self._get_v2_send_quota() if self._use_ses_v2 else self._get_v1_send_quota()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 323, in _get_v1_send_quota
    quota_dict = self.connection.get_send_quota()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetSendQuota operation: The security token included in the request is invalid.
```

***Second Traceback (with USE_SES_V2 = True):***
```
Internal Server Error: /app/
Traceback (most recent call last):
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/felix/Workspace/Stuff/django-ses-test/app/views.py", line 9, in index
    send_mail("test", "test", "felix.lehner1@gmail.com", ["felix.lehner1@gmail.com"], fail_silently=False)
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 161, in send_messages
    self._update_throttling()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 210, in _update_throttling
    rate_limit = self.get_rate_limit()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 305, in get_rate_limit
    return self._get_v2_send_quota() if self._use_ses_v2 else self._get_v1_send_quota()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/django_ses/__init__.py", line 315, in _get_v2_send_quota
    account_dict = self.connection.get_account()
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/felix/Workspace/Stuff/django-ses-test/venv/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetAccount operation: The security token included in the request is invalid.
```

Thanks for the quick answer!

**Comment by pcraciunoiu** [comment]
@peidrao @rodrigondec do you have any ideas? Thanks!

**Comment by Cyb3rFl3x** [comment]
Here is the codebase: https://github.com/Cyb3rFl3x/django-ses-example-code

**Comment by Cyb3rFl3x** [comment]
Hey Guys, did you already found a solution? I found this in my logs.
```
additional_headers 	{}
api_params 	{}
endpoint_url 'https://email.eu-central-1.amazonaws.com'
error_class <class 'botocore.exceptions.ClientError'>
error_code 'InvalidClientTokenId'
event_response None
handler <function inject_api_version_header_if_needed at 0x1024ce3a0>
http <botocore.awsrequest.AWSResponse object at 0x120f3ed30>
operation_model OperationModel(name=GetSendQuota)
operation_name 'GetSendQuota'
parsed_response

{
    'Error': {'Code': 'InvalidClientTokenId',
              'Message': 'The security token included in the request is invalid.',
              'Type': 'Sender'},
    'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
                                         'content-length': '305',
                                        'content-type': 'text/xml',
                                        'date': 'Fri, 26 May 2023 05:24:27 GMT',
                                        'x-amzn-requestid': 'bed0394b-e28c-47ff-a0dd-2b995ca20054'},
                         'HTTPStatusCode': 403,
                         'RequestId': 'bed0394b-e28c-47ff-a0dd-2b995ca20054',
                         'RetryAttempts': 0}}

request_context 	

{
    'auth_type': None,
    'client_config': <botocore.config.Config object at 0x120f1fd60>,
    'client_region': 'eu-central-1',
    'has_streaming_input': False,
    'retries': {'attempt': 1,
                'invocation-id': '9f515395-866a-4f39-a504-2dada7442e8c',
                'max': 5},
    'timestamp': '20230526T052427Z'
}

request_dict 	

{
    'body': {'Action': 'GetSendQuota', 'Version': '2010-12-01'},
    'context': {'auth_type': None,
                'client_config': <botocore.config.Config object at 0x120f1fd60>,
                'client_region': 'eu-central-1',
                'has_streaming_input': False,
                'retries': {'attempt': 1,
                            'invocation-id': '9f515395-866a-4f39-a504-2dada7442e8c',
                            'max': 5},
                'timestamp': '20230526T052427Z'},
    'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'User-Agent': 'Boto3/1.26.69 Python/3.9.6 Darwin/22.3.0 '
                'Botocore/1.29.69'},
    
 'method': 'POST',
 'query_string': '',
 'url': 'https://email.eu-central-1.amazonaws.com/',
 'url_path': '/'
 }
 ```

**Comment by rodrigondec** [comment]
Appears to be a error about the token used.

The values of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are correct? This key has SES permission on the AWS IAM?


On the code

https://github.com/Cyb3rFl3x/django-ses-example-code/blob/ae42d9a78fc145a75c6fe72882200f001a433afa/ses/settings.py#L117-L120

**Comment by Cyb3rFl3x** [comment]
Hey Rodrigo, I think the tokens are correct, because I can use the same one in AWS-CLI and with boto3 (raw_email) function in the same codebase.
```
# This is not working
def send_mail(plaintext, htmly, context, subject, to_email, from_email="my-email-address@gmail.com"): 
    text_content = plaintext.render(context)
    html_content = htmly.render(context)
    
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

# This works!
def send_mail_ses(plaintext, htmly, context, subject, to_email, from_email="my-email-address@gmail.com"):
    ses_client = boto3.client('ses')
    html_data = """Subject: Subscription
    MIME-Version: 1.0
    Content-Type: text/HTML
    <!DOCTYPE html>
        <html>
        <head>
            <style>
                h1   {color: #333;}
                p    {color: #555;}
            </style>
        </head>
        <body>
            <h1>Hi</h1>
            <p>you have subscribed to this newsletter.</p>
        </body>
    </html>
    """
    response = ses_client.send_raw_email(
        Source='my-email-address@gmail.com',
        Destinations=[
            'my-email-address@gmail.com',
        ],
        RawMessage={
            'Data': html_data
        }
    )
```

The code you are pointing to from my example is just a simplified code from the original. Here is the code from the original: 

```
AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY')
AWS_PRIMARY_REGION_NAME = env.str('AWS_PRIMARY_REGION_NAME')
```

I use this only because I have multiple other places where AWS keys are needed, and to centralize the key access from the settings file. It works for all other integrations like cloudwatch, s3, ...

Thanks for your help!

**Comment by jasongi** [comment]
I was getting a bunch of errors around this trying to run in a lambda, two things I did to solve them:

1. Ensure that the correct permissions were granted, in particular, ses:GetAccount and ses:GetSendQuota
2. Ensure AWS_SESSION_TOKEN was set (using the env var) in my django settings. E.g `AWS_SESSION_TOKEN = env.str('AWS_SESSION_TOKEN')

**Comment by rodrigondec** [comment]
Mark as solved?
